name: CI workflow
on: 
  workflow_run:
    workflows: ["unittests"]
    types:
      - completed
jobs:
  model_zoo_mxnet:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Download artifact(For push)
#        if: ${{ github.workflow_run.event = 'push' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: unittest.yml
#      - name: Download artifact(For pull request)
#        if: ${{ github.workflow_run.event = 'pull_request' || github.workflow_run.event = 'pull_request_target' }}
#        uses: dawidd6/action-download-artifact@v2
#        with:
      - name: View artifact
        run: |
          cat artifact.txt
      
#      - name: Checkout repository(For push)
#        if: ${{ github.event_name == 'push' }}
#        uses: actions/checkout@v2
#      - name: Checkout Pull Request Repository(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.event.pull_request.head.repo.full_name }}
#          ref: ${{ github.event.pull_request.head.ref }}
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.GLUONCV_DEV_ACCESS_ID }}
#          aws-secret-access-key: ${{ secrets.GLUONCV_DEV_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#      - name: Install dependencies
#        run: |
#          pip install --upgrade --force-reinstall --no-deps .
#          pip install boto3
#      - name: Test model_zoo_mxnet on AWS Batch(For push)
#        shell: bash -l {0}
#        if: ${{ github.event_name == 'push' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-ModelZooMxnet-${{ github.ref }} \
#                                             --source-ref ${{ github.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.repository }} \
#                                             --command "chmod +x ./.github/workflows/gpu_test.sh && ./.github/workflows/gpu_test.sh gluoncv tests/model_zoo" \
#                                             --wait
#      - name: Test model_zoo_mxnet on AWS Batch(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-ModelZooMxnet-PR#${{ github.event.number }} \
#                                             --source-ref ${{ github.event.pull_request.head.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.event.pull_request.head.repo.full_name }} \
#                                             --command "chmod +x ./.github/workflows/gpu_test.sh && ./.github/workflows/gpu_test.sh gluoncv tests/model_zoo" \
#                                             --wait
#  model_zoo_torch:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository(For push)
#        if: ${{ github.event_name == 'push' }}
#        uses: actions/checkout@v2
#      - name: Checkout Pull Request Repository(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.event.pull_request.head.repo.full_name }}
#          ref: ${{ github.event.pull_request.head.ref }}
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.GLUONCV_DEV_ACCESS_ID }}
#          aws-secret-access-key: ${{ secrets.GLUONCV_DEV_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#      - name: Install dependencies
#        run: |
#          pip install --upgrade --force-reinstall --no-deps .
#          pip install boto3
#      - name: Test model_zoo_torch on AWS Batch(For push)
#        shell: bash -l {0}
#        if: ${{ github.event_name == 'push' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-ModelZooTorch-${{ github.ref }} \
#                                             --source-ref ${{ github.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.repository }} \
#                                             --command "chmod +x ./.github/workflows/gpu_test.sh && ./.github/workflows/gpu_test.sh gluoncv/torch tests/model_zoo_torch" \
#                                             --wait
#      - name: Test model_zoo_torch on AWS Batch(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-ModelZooTorch-PR#${{ github.event.number }} \
#                                             --source-ref ${{ github.event.pull_request.head.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.event.pull_request.head.repo.full_name }} \
#                                             --command "chmod +x ./.github/workflows/gpu_test.sh && ./.github/workflows/gpu_test.sh gluoncv/torch tests/model_zoo_torch" \
#                                             --wait
#  auto:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository(For push)
#        if: ${{ github.event_name == 'push' }}
#        uses: actions/checkout@v2
#      - name: Checkout Pull Request Repository(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.event.pull_request.head.repo.full_name }}
#          ref: ${{ github.event.pull_request.head.ref }}
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.GLUONCV_DEV_ACCESS_ID }}
#          aws-secret-access-key: ${{ secrets.GLUONCV_DEV_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#      - name: Install dependencies
#        run: |
#          pip install --upgrade --force-reinstall --no-deps .
#          pip install boto3
#      - name: Test model_zoo_torch on AWS Batch(For push)
#        shell: bash -l {0}
#        if: ${{ github.event_name == 'push' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-Auto-${{ github.ref }} \
#                                             --source-ref ${{ github.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.repository }} \
#                                             --command "chmod +x ./.github/workflows/gpu_test.sh && ./.github/workflows/gpu_test.sh gluoncv tests/auto" \
#                                             --wait
#      - name: Test model_zoo_torch on AWS Batch(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-Auto-PR#${{ github.event.number }} \
#                                             --source-ref ${{ github.event.pull_request.head.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.event.pull_request.head.repo.full_name }} \
#                                             --command "chmod +x ./.github/workflows/gpu_test.sh && ./.github/workflows/gpu_test.sh gluoncv tests/auto" \
#                                             --wait
#  build-docs:
#    needs: [model_zoo_mxnet, model_zoo_torch, auto]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository(For push)
#        if: ${{ github.event_name == 'push' }}
#        uses: actions/checkout@v2
#      - name: Checkout Pull Request Repository(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.event.pull_request.head.repo.full_name }}
#          ref: ${{ github.event.pull_request.head.ref }}
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.GLUONCV_DEV_ACCESS_ID }}
#          aws-secret-access-key: ${{ secrets.GLUONCV_DEV_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#      - name: Install dependencies
#        run: |
#          pip install --upgrade --force-reinstall --no-deps .
#          pip install boto3
#      - name: Set SHA outputs
#        id: vars
#        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#      - name: Build docs on AWS Batch(For push)
#        shell: bash -l {0}
#        if: ${{ github.event_name == 'push' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-BuildDocs-${{ github.ref }} \
#                                             --source-ref ${{ github.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.repository }} \
#                                             --command "chmod +x ./.github/workflows/build_docs.sh && ./.github/workflows/build_docs.sh ${{ github.ref }} ${{ steps.vars.outputs.sha_short }} ${{ github.repository }} ${{ github.event.number }}" \
#                                             --wait
#      - name: Build docs on AWS Batch(For pull request)
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        run: |
#          echo "Start submitting job"
#          python ./tools/batch/submit-job.py --region us-east-1 \
#                                             --job-type p3.2x \
#                                             --name GluonCV-GPU-BuildDocs-PR#${{ github.event.number }} \
#                                             --source-ref ${{ github.event.pull_request.head.ref }} \
#                                             --work-dir . \
#                                             --remote https://github.com/${{ github.event.pull_request.head.repo.full_name }} \
#                                             --command "chmod +x ./.github/workflows/build_docs.sh && ./.github/workflows/build_docs.sh ${{ github.event.pull_request.head.ref }} ${{ steps.vars.outputs.sha_short }} ${{ github.event.pull_request.head.repo.full_name }} ${{ github.event.number }} " \
#                                             --wait
#      - name: Comment on PR
#        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
#        uses: peter-evans/create-or-update-comment@v1.4.3
#        with:
#          issue-number: ${{ github.event.number }}
#          body: |
#            Job PR-${{ github.event.number }}-${{ steps.vars.outputs.sha_short }} is done.
#            Docs are uploaded to http://gluon-vision-staging.s3-website-us-west-2.amazonaws.com/PR-${{ github.event.number }}/${{ steps.vars.outputs.sha_short }}/index.html
                        
